
INSERT OVERWRITE INTO
   $Database_Name.$Schema_Name.adwh_dim_date
SELECT
   cast(a.Date as date) Date_Key,
   cast(a.Date as timestamp) Date,
   a.date_date,
   a.DayOfMonth,
   a.DaySuffix,
   a.DayName,
   a.DayOfWeek,
   a.DayOfWeekUK,
   a.DayOfWeekInMonth,
   a.DayOfWeekInYear,
   a.DayOfQuarter,
   a.DayOfYear,
   a.WeekOfMonth,
   a.WeekOfQuarter,
   a.WeekOfYear,
   a.Month,
   a.MonthName,
   a.MonthOfQuarter,
   a.Quarter,
   a.QuarterName,
   a.Year,
   a.YearName,
   a.MonthYear,
   a.MMYYYY,
   to_date(a.FirstDayofWeek) FirstDayofWeek,
   to_date(a.LastDayofWeek) LastDayofWeek,
   to_date(a.FirstDayOfMonth) FirstDayOfMonth,
   to_date(a.LastDayOfMonth) LastDayOfMonth,
   to_date(a.FirstDayOfQuarter) FirstDayOfQuarter,
   to_date(a.LastDayOfQuarter) LastDayOfQuarter,
   to_date(a.FirstDayOfYear) FirstDayOfYear,
   to_date(a.LastDayOfYear) LastDayOfYear,
   a.IsHoliday,
   a.IsWeekday,
   a.Holiday,
   cast(a.FiscalDayOfYear as Int) FiscalDayOfYear,
   cast(a.FiscalDayOfWeek as Int) FiscalDayOfWeek,
   cast(a.FiscalDayOfMonth as Int) FiscalDayOfMonth,
   cast(a.FiscalDayOfQuarter as Int) FiscalDayOfQuarter,
   cast(a.FiscalWeekOfYear as Int) FiscalWeekOfYear,
   cast(a.FiscalMonth as Int) FiscalMonth,
   cast(a.FiscalQuarter as Int) FiscalQuarter,
   a.FiscalQuarterName,
   a.FiscalYear,
   a.FiscalYearName,
   a.FiscalMonthYear,
   a.FiscalMMYYYY,
   to_date(a.FiscalFirstDayOfWeek) FiscalFirstDayOfWeek,
   to_date(a.FiscalLastDayOfWeek) FiscalLastDayOfWeek,
   to_date(a.FiscalFirstDayOfMonth) FiscalFirstDayOfMonth,
   to_date(a.FiscalLastDayOfMonth) FiscalLastDayOfMonth,
   to_date(a.FiscalFirstDayOfQuarter) FiscalFirstDayOfQuarter,
   to_date(a.FiscalLastDayOfQuarter) FiscalLastDayOfQuarter,
   to_date(a.FiscalFirstDayOfYear) FiscalFirstDayOfYear,
   to_date(a.FiscalLastDayOfYear) FiscalLastDayOfYear,
   to_date(a.FiscalCurrentWeek) FiscalCurrentWeek,
   to_date(a.FiscalCurrentMonth) FiscalCurrentMonth,
   to_date(a.FiscalCurrentQuarter) FiscalCurrentQuarter,
   to_date(a.FiscalCurrentYear) FiscalCurrentYear,
   to_date(a.FiscalPrevWeek) FiscalPrevWeek,
   to_date(a.FiscalPrevMonth) FiscalPrevMonth,
   to_date(a.FiscalPrevQuarter) FiscalPrevQuarter,
   to_date(a.FiscalPrevYear) FiscalPrevYear,
   to_date(a.FiscalNextWeek) FiscalNextWeek,
   to_date(a.FiscalNextMonth) FiscalNextMonth,
   to_date(a.FiscalNextQuarter) FiscalNextQuarter,
   to_date(a.FiscalNextYear) FiscalNextYear,
   a.FiscalYearQuarter,
   a.FiscalYearMonth,
   a.FiscalYearWeek,
   cast(a.CurrentYear as int) CurrentYear,
   cast(a.CurrentQuarter as int) CurrentQuarter,
   cast(a.CurrentMonth as int) CurrentMonth,
   cast(a.CurrentWeek as int) CurrentWeek,
   cast(a.CurrentDay as int) CurrentDay
FROM
   $Source_Table_Name a;
